### ISSUE TITLE
Configuration flow not working, discovery not working.

### ISSUE THREAD

**Issue by sharonna511** [krahabb/meross_lan#224]
## Version of the custom_component
v2.6.2

## Version of home assistant
2022.4.6

## Configuration
None, not working to configure anything.

## Describe the bug
I have one device a MSS210 Plug, configured via meross app.
Meross LAN installed with Hacs.
Device is not discovered, also tried the 10s unplug multiple times.
Manual config does not work.

Error: This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Log shows the config flow has some problem.
Any ideas how to get it running ?
Possible to configure via yaml instead ?
Thanks

## Debug log
2022-11-10 11:17:34 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-10 11:17:34 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-10 11:17:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-10 11:17:36 WARNING (SyncWorker_4) [homeassistant.helpers.service] Unable to find services.yaml for the xiaomi_vacuum integration
2022-11-10 11:17:42 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration meross_lan: cannot import name 'CONF_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2022-11-10 11:17:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 743, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/meross_lan/config_flow.py", line 7, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'CONF_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 192, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 190, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 223, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 750, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2022-11-10 11:19:02 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration meross_lan: cannot import name 'CONF_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2022-11-10 11:27:03 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration meross_lan: cannot import name 'CONF_ERROR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by krahabb** [comment]
Hello @sharonna511,
That's a compatibility issue with HA 2022.4.x
I've recently restricted the backward compatibility to HA older releases but 'somehow' this restriction is not appearing in the component manifest and so the issue (ideally you shouldn't be allowed to install the latest meross_lan on older HA cores)
I need to review some code and the git versioning to see where this patch went missing, in the meantime I suggest you to update HA to one of the latest cores (or maybe you can't because of other issues ...just guessing...)

**Comment by sharonna511** [comment]
Thank you for your answer, i already had a feeling that it was the HA version. I am always reluctant to update HA because of breaking changes and breaking components, because i have so much stuff in it....
