### ISSUE TITLE
Devices unavailable on 3.0.0 (key is set)

### ISSUE THREAD

**Issue by boehser-enkel** [krahabb/meross_lan#253]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/meross_lan/__init__.py", line 523, in async_setup_entry
    device = api.build_device(device_id, entry)
  File "/config/custom_components/meross_lan/__init__.py", line 185, in build_device
    from .media_player import Mp3Mixin
  File "/config/custom_components/meross_lan/media_player.py", line 164, in <module>
    LightMixin, MerossDevice if typing.TYPE_CHECKING else object
NameError: name 'LightMixin' is not defined

**Comment by krahabb** [comment]
MMh...I really need to start automate testing :(
I guess there's a declaration error now that you point at it...
I'll test and patch right away

**Comment by boehser-enkel** [comment]
> MMh...I really need to start automate testing :( I guess there's a declaration error now that you point at it... I'll test and patch right away
> 
> P.S. the patch is really simple if you want to not wait for the 'official' one: on line 164 in media_player.py remove the comma and 'MerossDevice' so it shows like: `LightMixin if typing.TYPE_CHECKING else object`

That did the job. Thank you
