### ISSUE TITLE
Error setting up entry mss310h

### ISSUE THREAD

**Issue by marco0474** [krahabb/meross_lan#306]
Version 4.2.0
Already functional device suddenly stopped working. I searched through existing issues but didn't find anything similar. No recent updates no changes concerning wifi. The device just stopped connecting. Already tried uninstalling custom component but didn't work, tried factory resetting the device and reconnecting it to the Meross account but doesn't seem to change anything. Also tried recovering a backup but no success. Pls help me figure it out i'm not good in this field

Two error are found:

1) Logger: homeassistant.config_entries
Source: custom_components/meross_lan/meross_device.py:578
Integration: Meross LAN (documentation, issues)
First occurred: 18:20:45 (5 occurrences)
Last logged: 18:37:00

Error setting up entry mss310h - stampante for meross_lan
Traceback (most recent call last):
  File "/config/custom_components/meross_lan/helpers.py", line 586, in exception_warning
    yield
  File "/config/custom_components/meross_lan/meross_device.py", line 183, in __init__
    device_registry.async_get(ApiProfile.hass).async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 500, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 162, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'connections': {('mac', '34:29:8f:18:68:d5')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Plug (1811265489704629086934298f1868d5)', 'identifiers': {('meross_lan', '1811265489704629086934298f1868d5')}, 'model': 'mss310h 2.0.0', 'sw_version': '2.1.7', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 516, in async_setup_entry
    device = api.build_device(config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 402, in build_device
    device = class_type(descriptor, config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/switch.py", line 50, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/sensor.py", line 331, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/sensor.py", line 500, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/meross_device.py", line 351, in __init__
    super().__init__(
  File "/config/custom_components/meross_lan/meross_device.py", line 181, in __init__
    with self.exception_warning("DeviceRegistry.async_get_or_create"):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/config/custom_components/meross_lan/helpers.py", line 588, in exception_warning
    self.warning(
  File "/config/custom_components/meross_lan/meross_device.py", line 470, in warning
    LOGGER.warning(f"MerossDevice({self.name}): {msg}", *args, **kwargs)
                                   ^^^^^^^^^
  File "/config/custom_components/meross_lan/meross_device.py", line 207, in name
    return self._get_internal_name()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/meross_device.py", line 578, in _get_internal_name
    return self.descriptor.productname
           ^^^^^^^^^^^^^^^
AttributeError: 'ToggleXMixinElectricityMixinConsumptionMixinMerossDevice' object has no attribute 'descriptor'

2) Logger: aiohttp.server
Source: custom_components/meross_lan/config_flow.py:664
Integration: Meross LAN (documentation, issues)
First occurred: 18:22:28 (5 occurrences)
Last logged: 18:37:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 219, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 268, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/config_flow.py", line 540, in async_step_init
    return await self.async_step_device()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/config_flow.py", line 664, in async_step_device
    self._placeholders[CONF_DEVICE_TYPE] = device.descriptor.productnametype
                                           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'descriptor'

**Comment by townsmcp** [comment]
@krahabb in breaking changes section it mentions Python 3.10 support being removed on 2023.8.X - would this be the root cause?

**Comment by krahabb** [comment]
Not really...the issue lies in the way entities and devices record themselves in the HA device registry.
It looks like HA core is introducing some 'strict' requirements on how this should happen depending on the type of entity/device being registered.
