### ISSUE TITLE
light.turn_on service generates errors when parameters are used

### ISSUE THREAD

**Issue by dabbler68** [krahabb/meross_lan#357]
This is new with version 4.5. I just updated Core 2023.12.3 to 2023.12.4 and Meross LAN from 4.4.1 to 4.5 at the same time. Generic OS on Intel.

I have MSL420 and 430 lamps with simple automations to turn them on and set colour and brightness. 
The relevant YAML code from an automation is here (with correct indentation):
        sequence:
          - service: light.turn_on
            data:
              brightness: 30
            target:
              device_id: 1dxxxxxxx  (same result if using entity_id)

I have also tried:
              color_name: seagreen
              brightness_pct: 20

These previously worked fine but now also fail. The lights turn on but the parameters are ignored and the ERROR is generated. If no parameters are entered ( data: {}) no errors are generated. 

These worked before 4.5. I have also tried reloading the integration for the selected lamps. Also hard booted the OS.

Add your logs here.
2023-12-30 00:47:47.695 ERROR (MainThread) [homeassistant.components.automation.test_signal_lamps] Test signal lamps: Choose at step 1: choice 3: Error executing script. Unexpected error for call_service at pos 1: 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 174, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 903, in entity_service_call
    raise result from None
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/meross_lan/light.py", line 295, in async_turn_on
    togglex_response[mc.KEY_PAYLOAD][mc.KEY_TOGGLEX][0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by krahabb** [comment]
I think the issue should also come up in previous versions since the parsing code is more or less the same.
The difference is that previous versions had a different pipe were the error was trapped so the service wouldnt fail and you could see a warning log like "error in async_http_request......")
Even if annoying the fact that the service now abruptly fails has detected a subtle malfunctioning which was undetected before.

Thank you
