### ISSUE TITLE
mss110 7.0.0 by Meross Firmware: 7.3.37 Hardware: 7.0.0 

### ISSUE THREAD

**Issue by JosephRDawson** [krahabb/meross_lan#472]
This integration has topped working on my  mss110 on hardware version 7.0.0 running Firmware: 7.3.37.

The ability to control other Meross devices is not impacted.  

I am running a HA Green on the latest fully patched version of HA.

I have tried the latest version of this component and all beta versions with the same result sadly.

I have provided logs and debug information to the developer but unfortunately at this point the developer has not had other reports of others having the same issue on the latest version of the software.  For now I have been forced to switch to the cloud version of this integration until the issue can be resolved. 

If you are also experiencing this issue please post here so we can let the developer know and hopefully with more people reporting it we can find the common thread to the problem.

All the best,

Joe

**Comment by pbrooks29** [comment]
This integration stopped working when I updated to the latest version of the integration today. Don't think it has anything to do with the meross device firmware, I'm on hardware 8.0.0, firmware 8.3.5, but restarting HA throws the following early errors while trying to load the new version:
```

> 2024-07-10 18:31:07.163 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-07-10 18:31:48.599 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.meross_lan
> File "/config/custom_components/meross_lan/__init__.py", line 24, in <module>
> File "/config/custom_components/meross_lan/helpers/manager.py", line 395
> 2024-07-10 18:31:48.616 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration meross_lan: Unable to import component: Exception importing custom_components.meross_lan
> File "/config/custom_components/meross_lan/__init__.py", line 24, in <module>
> File "/config/custom_components/meross_lan/helpers/manager.py", line 395
> ImportError: Exception importing custom_components.meross_lan

```
Home Assistant 2023.10.0, was running integration version [Moonlight.2.2 (5.2.2)](https://github.com/krahabb/meross_lan/releases/tag/v5.2.2) upgraded to  [Moonlight.3](https://github.com/krahabb/meross_lan/releases/tag/v5.3.0) and restarted HA

**Comment by krahabb** [comment]
To avoid confusion and better clarify this issue/thread, the problem faced by @JosephRDawson is about toggling its mss110 devices (fw 7.3.37) from HA/meross_lan.
Everything else is working (@JosephRDawson pls correct me if I'm wrong):
- the device state is reported correctly when you toggle the device with the app or whatsoever
- there are no apparent errors in logs
- when you toggle the device from HA it 'simply' doesn't toggle (no errors reported)

If someone else is using the same device/firmware and is experiencing the same issue or, on the contrary, everything is working, please report the behavior.

**Comment by aholmes55** [comment]
I am having the identical issue.  Only with MSS110 devices.  My MSS120, MSS620 and MSS510 devices work correctly in HA/MerossLAN.   State changes in HA/MerossLAN are reflected correctly on the HA interface but attempts to change state through HA aren’t working.

**Comment by krahabb** [comment]
Hello @aholmes55,
If you could get a diagnostic from the device and upload a link I'd check it...not that I'm confident I would find the issue (I did inspect the diagnostic for the same kind of device from @JosephRDawson without any luck)
But maybe something else could 'pop up' 
Thank you for signaling the issue so that this doesn't get stale too much.

**Comment by aholmes55** [comment]
> Hello @aholmes55, If you could get a diagnostic from the device and upload a link I'd check it...not that I'm confident I would find the issue (I did inspect the diagnostic for the same kind of device from @JosephRDawson without any luck) But maybe something else could 'pop up' Thank you for signaling the issue so that this doesn't get stale too much.

Ugh - apologies.  I wasn't on 5.3.0 which is working perfectly on all my devices.  Thanks!

**Comment by winterminute** [comment]
I'm also hitting this issue with mss110 7.0.0 on 7.3.37.  I'm running latest of everything include this repo (5.3.1)

Here's my diagnostic info:

> 2024-09-30 00:20:11.070 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fe6df3d3b50>,) inside the event loop by custom integration 'meross_lan' at custom_components/meross_lan/merossclient/mqttclient.py, line 348: self.tls_set(cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLS_CLIENT) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/krahabb/meross_lan/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/meross_lan/__init__.py", line 586, in async_setup_entry
    device.start()
  File "/config/custom_components/meross_lan/meross_device.py", line 588, in start
    self._check_protocol_ext()
  File "/config/custom_components/meross_lan/meross_device.py", line 1693, in _check_protocol_ext
    profile.link(self)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1110, in link
    super().link(device)
  File "/config/custom_components/meross_lan/helpers/manager.py", line 606, in link
    device.profile_linked(self)
  File "/config/custom_components/meross_lan/meross_device.py", line 1667, in profile_linked
    self._check_protocol()
  File "/config/custom_components/meross_lan/meross_device.py", line 1732, in _check_protocol
    _profile.attach_mqtt(self)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1074, in attach_mqtt
    mqttconnection = self._get_mqttconnection(broker)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1240, in _get_mqttconnection
    return MerossMQTTConnection(self, broker)
  File "/config/custom_components/meross_lan/meross_profile.py", line 757, in __init__
    MerossMQTTAppClient.__init__(
  File "/config/custom_components/meross_lan/merossclient/mqttclient.py", line 348, in __init__
    self.tls_set(cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLS_CLIENT)


2024-09-30 20:47:39.164 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] TX(http) SET Appliance.Control.ToggleX (messageId:5b387a4e5bab478da3c67cae665750f5)
2024-09-30 20:47:39.204 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] HTTP ERROR SET Appliance.Control.ToggleX (messageId:5b387a4e5bab478da3c67cae665750f5 ServerDisconnectedError:Server disconnected)
2024-09-30 20:47:40.438 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] Polling begin
2024-09-30 20:47:40.439 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:e0cd2a11f7354bc7b305ebcfc0e692bc)
2024-09-30 20:47:40.488 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] HTTP ERROR SET Appliance.Control.Multiple (messageId:e0cd2a11f7354bc7b305ebcfc0e692bc ServerDisconnectedError:Server disconnected)
2024-09-30 20:47:40.489 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] Appliance.Control.Multiple failed with no response: requests=3 expected size=1260
2024-09-30 20:47:40.489 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] Updating device_response_size_max:1396
2024-09-30 20:47:40.489 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] TX(http) GET Appliance.Control.ToggleX (messageId:868b1c208d854f4fb7bf9402b6b4dbfb)
2024-09-30 20:47:40.529 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] HTTP ERROR GET Appliance.Control.ToggleX (messageId:868b1c208d854f4fb7bf9402b6b4dbfb ServerDisconnectedError:Server disconnected)
2024-09-30 20:47:40.529 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] TX(http) GET Appliance.Config.OverTemp (messageId:771da1c74f54483cb99ad5aeec1b4dc6)
2024-09-30 20:47:40.572 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] HTTP ERROR GET Appliance.Config.OverTemp (messageId:771da1c74f54483cb99ad5aeec1b4dc6 ServerDisconnectedError:Server disconnected)
2024-09-30 20:47:40.574 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] TX(http) GET Appliance.System.DNDMode (messageId:4f3b945d31a64f01988ff321cec3759f)
2024-09-30 20:47:40.616 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] HTTP ERROR GET Appliance.System.DNDMode (messageId:4f3b945d31a64f01988ff321cec3759f ServerDisconnectedError:Server disconnected)
2024-09-30 20:47:40.616 DEBUG (MainThread) [custom_components.meross_lan.mss110_###############################0] Polling end

**Comment by krahabb** [comment]
Hello @winterminute,
Could you provide a 'download diagnostic' (From HA mss110 device page) for the device?

**Comment by JosephRDawson** [comment]
Issue still not working for me... sadly...

**Comment by simongis** [comment]
I believe my issue is the same and is specific to MSS620 outdoor outlet, other outlets seem ok.  It has a fixed IP.

My dashboard buttons were no longer triggering the plug, and verified this was also the same in the device settings.

I had previously firmware on Meross devices and believe this correlates to when the issue started.  
Outlet still works fine from meross app and homekit.

firmware 7.3.8 from meross app, the home assistant device info still reporting 7.3.3
hardware - 7.0.0

[meross_lan-Smart Switch.json](https://github.com/user-attachments/files/18630809/meross_lan-Smart.Switch.json)

Trying to reconfigure:

![Image](https://github.com/user-attachments/assets/e4c0d2f7-cc4d-407f-8124-a523be25b924)

**Comment by krahabb** [comment]
@simongis,
I've opened a dedicated [issue](#526) since it looks different.

**Comment by simongis** [comment]
Thanks @krahabb 
Let me know if you want me to test anything or perform any specific steps.

**Comment by JosephRDawson** [comment]
@krahabb .... Any more updates on this?  Sadly 2025.3.0 has Broken Merros IOT Cloud intergration.  So I can't update to 2025.3.0 now.

I have a bunch of MS110 that are all on 7.3.46 now and will not work via your LAN interrogation. 

So you own any of the newer merros plugs that are impacted?

**Comment by JosephRDawson** [comment]
@krahabb I also tried restarting the devices after HA was running no change.  Also if i turn on and off the power to the device your integration sees the status change.  It just is not able to send commands to the devices that turn or off the power for some reason.

**Comment by krahabb** [comment]
Sadly no solution yet...

**Comment by JosephRDawson** [comment]
If you had one of the plugs to use would that help you?  PM me and I could send you a PayPal or something to pick one up. Perhaps if you did some local network sniffing on it you could figure it out.

**Comment by JosephRDawson** [comment]
By the way @krahabb do you know @albertogeniola of Meross IOT cloud integration? I ask because your both in the same country. What are the odds the two developers of HA add-ons for Meross are both in the same country.  :)  Their is an update to the dependencies he needs to make for the latest HA version.  But no one has been able to get in touch with him for weeks.  So we just are manually editing the dependency for now.

**Comment by JosephRDawson** [comment]
@krahabb  Is their anything I can do to help you figure this out? I would like to switch back to your integration.

**Comment by krahabb** [comment]
Hello @JosephRDawson,
Sorry for my delay replying..I'll consider buying an mss110 and don't worry about PayPal..they're so cheap and there's always some good use for them ;)

As for the Meross IOT cloud integration, sure I know that, and it's lower level meross_iot python library was one of the starting points for my work.
In the beginning it was the 'bible' for my knowledge of the Meross protocol and I'm so thankful to Alberto for its great work on reverse engineering the protocol so deeply.
We can say that meross_lan is a descendant of his work too, just a different approach in enegineeering the software but without his work meross_lan would have not been possible to develop.
Also, from time to time, for some issues, I've found his code more advanced than mine, expecially when the cloud api was changed some time ago or recently when some devices have introduced channel level encryption.
My work was mainly focused on developing the layers 'above' the protocol and I've never really got too deep in reverse engineering it with the tools and methods Alberto used instead. I just did some experiments/observations with the few devices I own but almost always by trial and error.

**Comment by JosephRDawson** [comment]
If you have an email for Alberto you can let him know people have placed the fix required for his code in github. He just needs to accept the integration. As for your code I don’t mind helping out anyway I can. I tried removing and re added devices. But no joy. It looks like the new firmware is doing something odd. What is interesting is that your integration still sees status changes. So i can use your integration as a trigger if the status changes. I just can’t control them through your integration. All the best,JoeOn Mar 14, 2025, at 7:05 PM, krahabb ***@***.***> wrote:﻿
  Hello @JosephRDawson,
Sorry for my delay replying..I'll consider buying an mss110 and don't worry about PayPal..they're so cheap and there's always some good use for them ;)
As for the Meross IOT cloud integration, sure I know that, and it's lower level meross_iot python library was one of the starting points for my work.
In the beginning it was the 'bible' for my knowledge of the Meross protocol and I'm so thankful to Alberto for its great work on reverse engineering the protocol so deeply.
We can say that meross_lan is a descendant of his work too, just a different approach in enegineeering the software but without his work meross_lan would have not been possible to develop.
Also, from time to time, for some issues, I've found his code more advanced than mine, expecially when the cloud api was changed some time ago or recently when some devices have introduced channel level encryption.
My work was mainly focused on developing the layers 'above' the protocol and I've never really got too deep in reverse engineering it with the tools and methods Alberto used instead. I just did some experiments/observations with the few devices I own but almost always by trial and error.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



krahabb left a comment (krahabb/meross_lan#472)
Hello @JosephRDawson,
Sorry for my delay replying..I'll consider buying an mss110 and don't worry about PayPal..they're so cheap and there's always some good use for them ;)
As for the Meross IOT cloud integration, sure I know that, and it's lower level meross_iot python library was one of the starting points for my work.
In the beginning it was the 'bible' for my knowledge of the Meross protocol and I'm so thankful to Alberto for its great work on reverse engineering the protocol so deeply.
We can say that meross_lan is a descendant of his work too, just a different approach in enegineeering the software but without his work meross_lan would have not been possible to develop.
Also, from time to time, for some issues, I've found his code more advanced than mine, expecially when the cloud api was changed some time ago or recently when some devices have introduced channel level encryption.
My work was mainly focused on developing the layers 'above' the protocol and I've never really got too deep in reverse engineering it with the tools and methods Alberto used instead. I just did some experiments/observations with the few devices I own but almost always by trial and error.

**Comment by JosephRDawson** [comment]
The fix to the HTTPs did it!
