### ISSUE TITLE
Detected blocking call to load_default_certs

### ISSUE THREAD

**Issue by browetd** [krahabb/meross_lan#486]
## Version of the custom_component
Meross_Lan: V5.3.1
HA: 2024.9.1
Supervisor: 2024.08.0
OS: 13.1
User Interface: 20240906.0

## Configuration
Using the Integration via Parameters, Tools and Services

Logs:

2024-09-07 08:26:54.550 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f1602ec6750>,) inside the event loop by custom integration 'meross_lan' at custom_components/meross_lan/merossclient/mqttclient.py, line 348: self.tls_set(cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLS_CLIENT) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/krahabb/meross_lan/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/meross_lan/__init__.py", line 586, in async_setup_entry
    device.start()
  File "/config/custom_components/meross_lan/meross_device.py", line 588, in start
    self._check_protocol_ext()
  File "/config/custom_components/meross_lan/meross_device.py", line 1693, in _check_protocol_ext
    profile.link(self)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1110, in link
    super().link(device)
  File "/config/custom_components/meross_lan/helpers/manager.py", line 606, in link
    device.profile_linked(self)
  File "/config/custom_components/meross_lan/meross_device.py", line 1667, in profile_linked
    self._check_protocol()
  File "/config/custom_components/meross_lan/meross_device.py", line 1732, in _check_protocol
    _profile.attach_mqtt(self)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1074, in attach_mqtt
    mqttconnection = self._get_mqttconnection(broker)
  File "/config/custom_components/meross_lan/meross_profile.py", line 1240, in _get_mqttconnection
    return MerossMQTTConnection(self, broker)
  File "/config/custom_components/meross_lan/meross_profile.py", line 757, in __init__
    MerossMQTTAppClient.__init__(
  File "/config/custom_components/meross_lan/merossclient/mqttclient.py", line 348, in __init__
    self.tls_set(cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLS_CLIENT)

```

## Describe the bug
Error while starting the integration but everything seems to work fine...
Using MSS310, MSH300HK, GS559A and MS200 devices...

**Comment by krahabb** [comment]
Yeah..thank you for signaling this..
This is due to the HA core deprecating every synchronous call in the main loop so the code have to be adapted.
right now it's just a warning/deprecation so everything should still work.
I'll add to the todo/fix workload ;)
