### ISSUE TITLE
MSH450 can't see gs559a smoke detector in home assistant

### ISSUE THREAD

**Issue by lethyro85** [krahabb/meross_lan#514]
in the Meross app i can see the gs559a, and it can be used with an MSH300, whitch is beside the msh450.
But in Homeassistant, it is not there. not idea :(

```yaml

2024-12-07 17:43:12.982 DEBUG (MainThread) [custom_components.meross_lan] async_unload_entry (entry_id:01JE9CJNZN33NN69A9NRVTWQ3H)
2024-12-07 17:43:12.984 DEBUG (MainThread) [custom_components.meross_lan.msh450_###############################4] mqtt_detached from ############0:@0
2024-12-07 17:43:12.984 DEBUG (MainThread) [custom_components.meross_lan.msh450_###############################4] unlinked from profile:#0
2024-12-07 17:43:12.984 DEBUG (MainThread) [custom_components.meross_lan.msh450_###############################4] Tracing end
2024-12-07 17:43:12.984 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry msh450 - 24071917018878620801c4e7ae072a68 for meross_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 649, in async_unload_entry
    return await manager.async_unload_entry(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/helpers/manager.py", line 331, in async_unload_entry
    await self.async_shutdown()
  File "/config/custom_components/meross_lan/devices/hub.py", line 240, in async_shutdown
    await super().async_shutdown()
  File "/config/custom_components/meross_lan/meross_device.py", line 705, in async_shutdown
    await super().async_shutdown()
  File "/config/custom_components/meross_lan/helpers/manager.py", line 261, in async_shutdown
    self.trace_close()
  File "/config/custom_components/meross_lan/meross_device.py", line 679, in trace_close
    super().trace_close()
  File "/config/custom_components/meross_lan/helpers/manager.py", line 474, in trace_close
    self._trace_future.set_result(self._trace_data)
asyncio.exceptions.InvalidStateError: invalid state


```

**Comment by krahabb** [comment]
Hello @lethyro85,
I don't get it, is the gs559a binded to the msh300 or to an msh450 ?
They should anyway behave the same as far as I know.

I see your log with the reported error which I'm not able to reproduce. At any rate, the diagnostic from the msh300 (or msh450) is really needed to try investigate why the gs559a doesn't appear.
The error here happens because teh system is shutting down while tracing is in progress...not sure why. Could you try get another diagnostic trace?
