### ISSUE TITLE
Meross MSG100 Garage door opener time out errors

### ISSUE THREAD

**Issue by Lordnnud** [krahabb/meross_lan#68]
I am suddenly getting these error messages. Did an upgrade to v2.2.1 no change. The Meros App can still talk to the device.

2021-09-05 13:10:43 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1341446-de33846d1b02e25592107d1a1368e4f0/subscribe", "messageId": "843876df9821f2a13b8cd42213270d6b", "method": "SET", "namespace": "Appliance.GarageDoor.State", "payloadVersion": 1, "sign": "e9057b2e78e4cab050f9273ee59e74aa", "timestamp": 1630843838, "triggerSrc": "Android"}, "payload": {"state": {"channel": 0, "open": 1, "uuid": "2011123333504136100848e1e93b1f6b"}}}' sent to device uuid 2011123333504136100848e1e93b1f6b. Timeout was: 5 seconds.
2021-09-05 13:10:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140331396815360] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 630, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/meross_cloud/cover.py", line 129, in async_open_cover
    await self._device.async_open(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/garage.py", line 67, in async_open
    await self._async_operate(state=True, channel=channel, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/garage.py", line 81, in _async_operate
    await self._execute_command(method="SET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 227, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 621, in async_execute_cmd
    response = await self._async_send_and_wait_ack(future=fut,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 634, in _async_send_and_wait_ack
    raise CommandTimeoutError()
meross_iot.model.exception.CommandTimeoutError

Can you help?

**Comment by krahabb** [comment]
Hello @Lordnnud,
it looks like this is not a meross_lan issue but the log states it comes from meross_iot which in turn comes from meross_cloud so I'm sorry to say I can't really help

`2021-09-05 13:10:43 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header": {"from": "/app/1341446-de33846d1b02e25592107d1a1368e4f0/subscribe", "messageId": "843876df9821f2a13b8cd42213270d6b", "method": "SET", "namespace": "Appliance.GarageDoor.State", "payloadVersion": 1, "sign": "e9057b2e78e4cab050f9273ee59e74aa", "timestamp": 1630843838, "triggerSrc": "Android"}, "payload": {"state": {"channel": 0, "open": 1, "uuid": "2011123333504136100848e1e93b1f6b"}}}' sent to device uuid 2011123333504136100848e1e93b1f6b. Timeout was: 5 seconds.`

**Comment by Lordnnud** [comment]
Thank you for decoding the log and pointing me in the right direction. Indeed reinstall of Meross Cloud IoT has resolved the problem.
